In [1]:
import numpy as np

In [2]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
X = np.arange(15).reshape(3, 5)
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

## 基本属性

In [6]:
x.ndim # 查看数据是几维数组

1

In [7]:
X.ndim

2

In [8]:
x.shape # 查看数组维度，返回元组

(10,)

In [9]:
X.shape

(3, 5)

In [10]:
x.size # 表示元素个数

10

In [11]:
X.size

15

## Numpy.array 的数据访问

In [12]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
x[0]

0

In [14]:
x[-1] # 负值表示倒数

9

In [15]:
X[0][0]

0

In [16]:
X[(0, 0)]

0

In [17]:
X[(2, 2)]

12

In [19]:
X[2, 2] # 建议使用这种方式访问元素

12

In [20]:
x[0:5]

array([0, 1, 2, 3, 4])

In [21]:
x[:5]

array([0, 1, 2, 3, 4])

In [22]:
x[5:]

array([5, 6, 7, 8, 9])

In [23]:
x[::2]

array([0, 2, 4, 6, 8])

In [24]:
X[:2, :3]

array([[0, 1, 2],
       [5, 6, 7]])

In [25]:
X[:2][:3] # 两个 [][] 不能表达语义

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [26]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [27]:
X[::-1, ::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [28]:
X[0, :]

array([0, 1, 2, 3, 4])

In [29]:
X[:, 0]

array([ 0,  5, 10])

In [30]:
subX = X[:2, :3]
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [31]:
subX[0, 0] = 100
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [32]:
X # Numpy 修改子矩阵会修改原矩阵

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [33]:
# 创建不相关的矩阵
subX = X[:2, :3].copy()
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [35]:
subX[0, 0] = 0
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [36]:
X # 并未发生变化

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

## Reshape 变换数组维度

In [37]:
x.shape

(10,)

In [38]:
x.ndim

1

In [39]:
x.reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [41]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
A = x.reshape(2, 5)

In [43]:
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [44]:
A.shape

(2, 5)

In [45]:
x.reshape(10, -1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])