# 1.Array(数组)
- rank: 数组的纬度

In [1]:
import numpy as np

In [2]:
a = np.array([1, 2, 3])

In [3]:
a

array([1, 2, 3])

In [4]:
type(a)

numpy.ndarray

In [34]:
# 查看数组纬度
a.shape

(3, 4)

In [35]:
# 重置数组纬度
a = a.reshape([1, -1])

In [7]:
a

array([[1, 2, 3]])

In [8]:
a.shape

(1, 3)

In [9]:
a = np.array([1, 2, 3, 4, 5, 6])

In [10]:
a.shape

(6,)

In [11]:
a = a.reshape(2, -1)

In [12]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [13]:
a.shape

(2, 3)

In [14]:
a = a.reshape(-1, 2)

In [15]:
a

array([[1, 2],
       [3, 4],
       [5, 6]])

In [16]:
a.shape

(3, 2)

In [17]:
a[2,0]

5

In [18]:
a[2,0] = 55

In [19]:
a

array([[ 1,  2],
       [ 3,  4],
       [55,  6]])

# 2.创建数组的方法
1. zeros：创建全为0的数组（向量、矩阵）
2. ones：创建全为1的数组（向量、矩阵）
3. full: 创建自定义的全部为某个值的数组（向量、矩阵）
4. eye: 创建单位矩阵
5. random.random：创建随机0-1之间的随机数组（向量、矩阵）

## 1.zeros

In [21]:
a = np.zeros((3, 3))

In [22]:
a

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

## 2.ones

In [23]:
a = np.ones((3, 3))

In [24]:
a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## 3.full

In [25]:
a = np.full((3,3),0)

In [26]:
a

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [27]:
a = np.full((2,3),3)

In [28]:
a

array([[3, 3, 3],
       [3, 3, 3]])

## 4.eye

In [29]:
a = np.eye(3)

In [30]:
a

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

## 5.random.random

In [32]:
a = np.random.random((3, 4))

In [33]:
a

array([[0.40705802, 0.97594901, 0.0361563 , 0.22676264],
       [0.90260695, 0.62326302, 0.75762833, 0.38878393],
       [0.3280271 , 0.7463639 , 0.4547792 , 0.82751356]])